-- Migration 010: add entry_header column to resume_bullets
-- Stores the pre-formatted LaTeX entry header (e.g. \job{Company}{Role}{Date})
-- generated by the LLM using template macros. Non-NULL only for the first bullet
-- of each source_entry_id group; subsequent bullets from the same entry are NULL.
ALTER TABLE resume_bullets
    ADD COLUMN IF NOT EXISTS entry_header TEXT;

COMMENT ON COLUMN resume_bullets.entry_header IS
    'Pre-formatted LaTeX entry header using template macros (\job, \project, etc.).
     Non-NULL only on the first bullet of each source_entry group. NULL on subsequent bullets.';
